import type { Metadata } from 'next';
import './globals.css';

import ReactQueryProvider from '@/providers/reactQuery';

import { Theme } from '@radix-ui/themes';
import { ThemeProvider } from 'next-themes';
import NavBar from '@/components/nav/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`min-h-screen`}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            value={{ light: 'light', dark: 'dark' }}
          >
            <Theme accentColor='purple'>{children}</Theme>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
